"use client";

import { useState } from "react";
import { ArrowLeft, Check, CheckCircle2, Phone, ReceiptText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatNaira } from "@/lib/utils";

export default function OrderDetail() {
  const [fulfilled, setFulfilled] = useState(false);
  return <div className="mx-auto max-w-3xl"><Button href="/dashboard/orders" tone="ghost" size="sm" className="-ml-3"><ArrowLeft size={16}/>All orders</Button><div className="card mt-5 overflow-hidden"><div className="border-b border-slate-200 p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-indigo-700">Order details</p><h1 className="mt-2 text-3xl font-bold">#HMG-1023</h1><p className="mt-2 text-sm text-slate-500">Placed today at 11:42 AM</p></div><div className="flex gap-2"><Badge tone="success">PAID</Badge><Badge tone={fulfilled?"success":"neutral"}>{fulfilled?"FULFILLED":"PENDING"}</Badge></div></div></div><div className="grid gap-6 p-6 sm:grid-cols-2 sm:p-8"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Customer</p><p className="mt-3 font-bold">Tolu Ajayi</p><a href="tel:08032145670" className="mt-2 flex items-center gap-2 text-sm text-indigo-700"><Phone size={15}/>080 3214 5670</a></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Fulfillment</p><p className="mt-3 font-bold">Pickup</p><p className="mt-2 text-sm text-slate-500">Sunday · 1:00–3:00 PM</p></div></div><div className="border-y border-slate-200 bg-slate-50 p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Items</p><div className="mt-4 space-y-4">{[["Smoky Jollof + Chicken",2,550000],["House Chapman",1,200000]].map(([name,qty,price])=><div key={String(name)} className="flex justify-between gap-4"><div><p className="font-semibold">{name}</p><p className="text-sm text-slate-500">Qty {qty}</p></div><strong>{formatNaira(Number(qty)*Number(price))}</strong></div>)}</div><div className="mt-6 border-t border-slate-200 pt-4"><div className="flex justify-between text-sm text-slate-500"><span>Subtotal</span><span>₦13,000</span></div><div className="mt-3 flex justify-between text-xl font-bold"><span>Total</span><span>₦13,000</span></div></div></div><div className="p-6 sm:p-8">{fulfilled?<div className="flex items-center justify-center gap-2 rounded-[10px] bg-emerald-50 p-4 font-semibold text-emerald-700"><CheckCircle2 size={20}/>Order marked as fulfilled</div>:<Button onClick={()=>setFulfilled(true)} className="w-full"><Check size={17}/>Mark as fulfilled</Button>}<p className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-400"><ReceiptText size={14}/>Payment reference PSK_89JGT2K</p></div></div></div>;
}
