import { notFound } from "next/navigation";
import { ArrowLeft, Phone, ReceiptText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FulfillButton } from "@/components/dashboard/fulfill-button";
import { requireVendor } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { formatNaira } from "@/lib/utils";

export default async function OrderDetail({params}:{params:Promise<{id:string}>}){const{vendor}=await requireVendor();const{id}=await params;const order=await db.order.findFirst({where:{id,vendorId:vendor.id},include:{items:true,payments:{where:{status:"SUCCESS"},take:1}}});if(!order)notFound();return <div className="mx-auto max-w-3xl"><Button href="/dashboard/orders" tone="ghost" className="-ml-3"><ArrowLeft size={16}/>All orders</Button><div className="card mt-5 overflow-hidden"><div className="border-b p-6 sm:p-8"><div className="flex justify-between gap-4"><div><p className="eyebrow text-indigo-700">Order details</p><h1 className="mt-2 text-3xl font-bold">#{order.orderNumber}</h1><p className="mt-2 text-sm text-slate-500">Placed {order.createdAt.toLocaleString()}</p></div><div className="flex gap-2"><Badge tone={order.status==="PAID"?"success":"warning"}>{order.status}</Badge><Badge tone={order.fulfillmentStatus==="FULFILLED"?"success":"neutral"}>{order.fulfillmentStatus}</Badge></div></div></div><div className="grid gap-6 p-6 sm:grid-cols-2 sm:p-8"><div><p className="eyebrow text-slate-400">Customer</p><p className="mt-3 font-bold">{order.customerName}</p><a href={`tel:${order.customerPhone}`} className="mt-2 flex items-center gap-2 text-sm text-indigo-700"><Phone size={15}/>{order.customerPhone}</a></div><div><p className="eyebrow text-slate-400">Fulfillment</p><p className="mt-3 font-bold">{order.fulfillmentType}</p><p className="mt-2 text-sm text-slate-500">{order.deliveryAddress||"Customer will pick up"}</p></div></div><div className="border-y bg-slate-50 p-6 sm:p-8"><p className="eyebrow text-slate-400">Items</p><div className="mt-4 space-y-4">{order.items.map(item=><div key={item.id} className="flex justify-between"><div><p className="font-semibold">{item.productName}</p><p className="text-sm text-slate-500">Qty {item.quantity}</p></div><strong>{formatNaira(item.lineTotalKobo)}</strong></div>)}</div><div className="mt-6 flex justify-between border-t pt-4 text-xl font-bold"><span>Total</span><span>{formatNaira(order.totalKobo)}</span></div></div><div className="p-6 sm:p-8"><FulfillButton orderId={order.id} fulfilled={order.fulfillmentStatus==="FULFILLED"}/><p className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-400"><ReceiptText size={14}/>{order.payments[0]?.providerReference||"Awaiting payment"}</p></div></div></div>}
