"use client";
import { useState } from "react";
import { ArrowRight, Check, Landmark, Link2, MessageCircle, Store } from "lucide-react";
import { Logo } from "@/components/brand/logo";
import { Button } from "@/components/ui/button";
import { Field, Input, Select } from "@/components/ui/form-field";

const content = [
  { icon: Store, eyebrow: "Step 1 of 4", title: "What should customers call your business?", copy: "This will appear at the top of every storefront.", fields: <><Field label="Business name"><Input defaultValue="Amaka's Kitchen"/></Field><Field label="Business category"><Select defaultValue="food"><option value="food">Food & catering</option><option>Fashion & thrift</option><option>Farm produce</option><option>Beauty & cosmetics</option><option>Other</option></Select></Field></> },
  { icon: Link2, eyebrow: "Step 2 of 4", title: "Claim your Hemigo link", copy: "Keep it short, memorable, and easy to share.", fields: <Field label="Store link"><div className="flex overflow-hidden rounded-[10px] border border-slate-200"><span className="flex items-center bg-slate-50 px-3 text-sm text-slate-500">hemigo.ng/</span><Input defaultValue="amaka-kitchen" className="rounded-none border-0"/></div></Field> },
  { icon: MessageCircle, eyebrow: "Step 3 of 4", title: "How should customers reach you?", copy: "We’ll show the right contact details after an order.", fields: <><Field label="Phone number"><Input defaultValue="080 3214 5670"/></Field><Field label="WhatsApp number"><Input defaultValue="080 3214 5670"/></Field><Field label="Contact email (optional)"><Input type="email" placeholder="orders@amakaskitchen.com"/></Field></> },
  { icon: Landmark, eyebrow: "Step 4 of 4", title: "Where should we send your money?", copy: "Test mode is on—no real payout details are stored.", fields: <><Field label="Bank"><Select><option>Guaranty Trust Bank</option><option>Access Bank</option><option>First Bank</option><option>Kuda</option></Select></Field><Field label="Account number"><Input inputMode="numeric" defaultValue="0123456789"/></Field><div className="rounded-[10px] bg-emerald-50 p-4 text-sm text-emerald-800"><Check className="mr-2 inline" size={17}/>Account name: AMAKA OKAFOR</div></> },
];
export default function Onboarding(){const[step,setStep]=useState(0);const item=content[step];const Icon=item.icon;return <main className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="container-shell flex h-18 items-center justify-between"><Logo/><button className="text-sm font-semibold text-slate-500">Save & exit</button></div></header><div className="container-shell grid gap-12 py-12 lg:grid-cols-[.7fr_1.3fr]"><aside><div className="sticky top-28"><span className="grid size-12 place-items-center rounded-[12px] bg-indigo-100 text-indigo-700"><Icon/></span><p className="eyebrow mt-7 text-indigo-700">{item.eyebrow}</p><h1 className="mt-3 text-4xl font-bold leading-tight tracking-[-.05em]">{item.title}</h1><p className="mt-4 leading-7 text-slate-500">{item.copy}</p></div></aside><section className="card p-6 sm:p-10"><div className="grid min-h-[320px] content-start gap-6">{item.fields}</div><div className="mt-8 flex items-center justify-between border-t border-slate-100 pt-6"><div className="flex gap-1.5">{content.map((_,i)=><span key={i} className={`h-1.5 rounded-full ${i<=step?"w-8 bg-indigo-600":"w-4 bg-slate-200"}`}/>)}</div><Button href={step===3?"/dashboard":undefined} onClick={()=>step<3&&setStep(step+1)}>{step===3?"Open my dashboard":"Continue"}<ArrowRight size={17}/></Button></div></section></div></main>}
