import { ArrowLeft, Download, Printer, Users, WalletCards } from "lucide-react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { foodProducts } from "@/lib/demo-data";

export default function FulfillmentPage() {
  return <div className="space-y-7"><div><Button href="/dashboard/windows" tone="ghost" size="sm" className="-ml-3"><ArrowLeft size={16}/>Selling windows</Button><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow text-indigo-700">Fulfillment plan</p><h1 className="mt-2 text-3xl font-bold tracking-[-.04em]">Sunday Lunch Batch</h1><p className="mt-2 text-slate-500">Everything you need to prepare, totalled up.</p></div><div className="flex gap-2"><Button tone="secondary"><Printer size={16}/>Print</Button><Button tone="secondary"><Download size={16}/>Export CSV</Button></div></div></div>
    <div className="grid gap-3 sm:grid-cols-2"><div className="card flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-[10px] bg-indigo-50 text-indigo-700"><Users size={20}/></span><div><p className="text-sm text-slate-500">Customers</p><strong className="text-2xl">42</strong></div></div><div className="card flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-[10px] bg-emerald-50 text-emerald-700"><WalletCards size={20}/></span><div><p className="text-sm text-slate-500">Paid revenue</p><strong className="text-2xl">₦286,500</strong></div></div></div>
    <section className="card overflow-hidden"><div className="border-b border-slate-200 bg-indigo-700 p-6 text-white"><p className="eyebrow text-indigo-200">What you need to prepare</p><h2 className="mt-2 text-2xl font-bold">128 items across 42 orders</h2></div><div className="divide-y divide-slate-100">{foodProducts.map((product,i)=><div key={product.id} className="flex items-center gap-4 p-5 sm:p-6"><Image src={product.image} alt="" width={64} height={64} className="size-16 rounded-[10px] object-cover"/><div className="min-w-0 flex-1"><h3 className="font-bold">{product.name}</h3><p className="mt-1 text-sm text-slate-500">From {i===0?31:i===1?22:i===2?27:18} customer orders</p></div><div className="text-right"><strong className="text-3xl tracking-tight">{product.sold}</strong><p className="text-xs font-semibold text-slate-500">{product.unit ?? "items"}</p></div></div>)}</div><div className="bg-amber-50 p-5 text-sm text-amber-900"><strong>Quick check:</strong> 8 paid orders are still waiting to be fulfilled.</div></section>
  </div>;
}
