import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowLeft, Download, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PrintButton } from "@/components/dashboard/print-button";
import { requireVendor } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { formatNaira } from "@/lib/utils";
export default async function FulfillmentPage({params}:{params:Promise<{id:string}>}){const{vendor}=await requireVendor();const{id}=await params;const window=await db.sellingWindow.findFirst({where:{id,vendorId:vendor.id},include:{orders:{where:{status:"PAID"},include:{items:true}}}});if(!window)notFound();const totals=new Map<string,{name:string;qty:number;orders:Set<string>;image:string}>();for(const order of window.orders)for(const item of order.items){const current=totals.get(item.windowProductId)??{name:item.productName,qty:0,orders:new Set<string>(),image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=300&q=80"};current.qty+=item.quantity;current.orders.add(order.id);totals.set(item.windowProductId,current)}const revenue=window.orders.reduce((s,o)=>s+o.totalKobo,0);return <div className="space-y-7"><Button href="/dashboard/windows" tone="ghost"><ArrowLeft size={16}/>Selling windows</Button><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow text-indigo-700">Fulfillment plan</p><h1 className="mt-2 text-3xl font-bold">{window.name}</h1><p className="mt-2 text-slate-500">Everything you need to prepare, totalled up from paid orders.</p></div><div className="flex gap-2"><PrintButton/><Button href={`/api/dashboard/windows/${window.id}/fulfillment/export`} tone="secondary"><Download size={16}/>Export CSV</Button></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="card flex items-center gap-4 p-5"><Users className="text-indigo-700"/><div><p className="text-sm text-slate-500">Customers</p><strong className="text-2xl">{window.orders.length}</strong></div></div><div className="card flex items-center gap-4 p-5"><WalletCards className="text-emerald-700"/><div><p className="text-sm text-slate-500">Paid revenue</p><strong className="text-2xl">{formatNaira(revenue)}</strong></div></div></div><section className="card overflow-hidden"><div className="bg-indigo-700 p-6 text-white"><p className="eyebrow text-indigo-200">What you need to prepare</p><h2 className="mt-2 text-2xl font-bold">{Array.from(totals.values()).reduce((s,i)=>s+i.qty,0)} items across {window.orders.length} orders</h2></div>{totals.size?<div className="divide-y">{Array.from(totals.values()).map(item=><div key={item.name} className="flex items-center gap-4 p-5"><Image src={item.image} alt="" width={64} height={64} className="size-16 rounded-lg object-cover"/><div className="flex-1"><h3 className="font-bold">{item.name}</h3><p className="text-sm text-slate-500">From {item.orders.size} customer orders</p></div><div className="text-right"><strong className="text-3xl">{item.qty}</strong><p className="text-xs text-slate-500">items</p></div></div>)}</div>:<div className="p-10 text-center text-slate-500">Paid order totals will appear here.</div>}</section></div>}
