import Link from "next/link";
import { PackageCheck, ReceiptText } from "lucide-react";
import { Navbar } from "@/components/marketing/navbar";
import { Badge } from "@/components/ui/badge";
import { requireUser } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { formatNaira } from "@/lib/utils";

export default async function PurchasesPage(){const user=await requireUser();const[hasVendor,orders]=await Promise.all([db.vendorMember.findFirst({where:{userId:user.id},select:{id:true}}),db.order.findMany({where:{customerUserId:user.id},include:{vendor:true,window:true,_count:{select:{items:true}}},orderBy:{createdAt:"desc"}})]);return <main className="min-h-screen bg-slate-50"><Navbar user={{name:user.name||user.email,hasVendor:Boolean(hasVendor)}}/><section className="container-shell py-12"><p className="eyebrow text-indigo-700">Your account</p><h1 className="mt-2 text-4xl font-bold">My purchases</h1><p className="mt-2 text-slate-500">Orders, invoices, receipts and fulfillment updates in one place.</p>{orders.length?<div className="mt-8 grid gap-4">{orders.map(order=><Link key={order.id} href={`/order/${order.publicToken}`} className="card flex flex-col gap-5 p-5 transition hover:border-indigo-200 sm:flex-row sm:items-center"><span className="grid size-12 place-items-center rounded-[12px] bg-indigo-50 text-indigo-700"><PackageCheck/></span><div className="flex-1"><p className="font-bold">{order.vendor.name} · {order.window.name}</p><p className="mt-1 text-sm text-slate-500">#{order.orderNumber} · {order._count.items} items · {order.createdAt.toLocaleDateString("en-NG")}</p></div><div className="flex items-center gap-3"><strong>{formatNaira(order.totalKobo)}</strong><Badge tone={order.status==="PAID"?"success":"warning"}>{order.status}</Badge></div></Link>)}</div>:<div className="card mt-8 p-14 text-center"><ReceiptText className="mx-auto text-indigo-300" size={40}/><h2 className="mt-4 text-xl font-bold">No purchases yet.</h2><p className="mt-2 text-slate-500">Orders placed while signed in will appear here.</p><Link href="/explore" className="mt-5 inline-block font-semibold text-indigo-700">Explore Hemigos</Link></div>}</section></main>}
