"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { AuthShell } from "@/components/auth/auth-shell";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/form-field";

export default function Login(){const[error,setError]=useState("");const[busy,setBusy]=useState(false);const router=useRouter();const search=useSearchParams();async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:data.get("email"),password:data.get("password")})});const result=await response.json();if(!response.ok){setError(result.error??"Could not log you in.");setBusy(false);return}const requested=search.get("next");router.push(requested?.startsWith("/")&&!requested.startsWith("//")?requested:"/dashboard");router.refresh()}const next=search.get("next");return <AuthShell quote="Now I open my dashboard and every order is already matched to a payment."><p className="eyebrow text-indigo-700">Welcome back</p><h1 className="mt-3 text-4xl font-bold tracking-[-.05em]">Your store is waiting.</h1><p className="mt-3 text-slate-500">Log in to keep your next batch moving.</p><form onSubmit={submit} className="mt-8 grid gap-5"><Field label="Email address"><Input name="email" type="email" placeholder="amaka@example.com" autoComplete="email" required/></Field><Field label="Password"><Input name="password" type="password" placeholder="At least 8 characters" autoComplete="current-password" required/></Field>{error&&<p role="alert" className="rounded-[9px] bg-red-50 p-3 text-sm font-medium text-red-700">{error}</p>}<Button type="submit" disabled={busy} size="lg" className="mt-2 w-full">{busy?"Logging in…":"Log in"}</Button></form><Link href="/forgot-password" className="mt-4 block text-center text-sm font-semibold text-indigo-700">Forgot password?</Link><div className="my-5 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200"/>or<span className="h-px flex-1 bg-slate-200"/></div><Button href={`/api/auth/google${next?`?next=${encodeURIComponent(next)}`:""}`} tone="secondary" className="w-full">G&nbsp;&nbsp;Continue with Google</Button><p className="mt-6 text-center text-sm text-slate-500">New to Hemigo? <Link href="/signup" className="font-semibold text-indigo-700">Start selling</Link></p></AuthShell>}
