import { notFound } from "next/navigation";
import { Clock3, FileText } from "lucide-react";
import { Logo } from "@/components/brand/logo";
import { Badge } from "@/components/ui/badge";
import { PayInvoiceButton } from "@/components/storefront/pay-invoice-button";
import { PrintButton } from "@/components/dashboard/print-button";
import { db } from "@/lib/db";
import { formatNaira } from "@/lib/utils";

export default async function InvoicePage({params}:{params:Promise<{token:string}>}){
  const{token}=await params;const invoice=await db.invoice.findUnique({where:{publicToken:token},include:{vendor:true,order:{include:{items:true}}}});if(!invoice)notFound();const payable=invoice.status==="UNPAID"&&invoice.dueAt>new Date()&&invoice.order.status==="RESERVED";
  return <main className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-2xl"><header className="mb-7 flex items-center justify-between"><Logo/><PrintButton/></header><section className="card overflow-hidden"><div className="flex flex-col justify-between gap-5 border-b p-6 sm:flex-row"><div><p className="eyebrow text-indigo-700">Invoice</p><h1 className="mt-2 text-2xl font-bold">{invoice.invoiceNumber}</h1><p className="mt-1 text-sm text-slate-500">Issued by {invoice.vendor.name}</p></div><Badge tone={invoice.status==="PAID"?"success":payable?"warning":"neutral"}>{invoice.status}</Badge></div><div className="p-6"><div className="mb-6 grid gap-4 rounded-[12px] bg-slate-50 p-5 sm:grid-cols-2"><div><p className="text-xs text-slate-500">Bill to</p><p className="mt-1 font-bold">{invoice.order.customerName}</p><p className="text-sm text-slate-500">{invoice.order.customerEmail}</p></div><div className="sm:text-right"><p className="text-xs text-slate-500">Due</p><p className="mt-1 font-bold">{invoice.dueAt.toLocaleString("en-NG")}</p>{payable&&<p className="mt-1 flex items-center gap-1 text-xs text-amber-700 sm:justify-end"><Clock3 size={13}/>{invoice.order.inventoryReserved?"Stock held until then":"Availability checked when you pay"}</p>}</div></div><div className="divide-y">{invoice.order.items.map(item=><div key={item.id} className="flex justify-between gap-4 py-4"><div><p className="font-semibold">{item.productName}</p><p className="text-sm text-slate-500">{item.quantity} × {formatNaira(item.unitPriceKobo)}</p></div><strong>{formatNaira(item.lineTotalKobo)}</strong></div>)}</div><div className="mt-4 flex justify-between border-t pt-5 text-2xl font-bold"><span>Total</span><span>{formatNaira(invoice.amountKobo)}</span></div><div className="mt-7">{payable?<PayInvoiceButton orderId={invoice.orderId}/>:invoice.status==="PAID"?<div className="rounded-[10px] bg-emerald-50 p-4 text-center font-semibold text-emerald-700">This invoice has been paid.</div>:<div className="rounded-[10px] bg-slate-100 p-4 text-center font-semibold text-slate-600">This invoice can no longer be paid.</div>}</div></div></section><p className="mt-5 flex items-center justify-center gap-2 text-xs text-slate-400"><FileText size={14}/>Generated automatically by Hemigo</p></div></main>
}
