"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/form-field";

export default function NewProductPage() {
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [type,setType]=useState("PHYSICAL");const[events,setEvents]=useState<Array<{id:string;name:string;startsAt:string}>>([]); const router=useRouter();
  useEffect(()=>{fetch("/api/dashboard/events").then(response=>response.json()).then(body=>setEvents(body.events||[]))},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);const response=await fetch("/api/dashboard/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),description:f.get("description"),type,defaultPriceNaira:f.get("price"),imageUrl:f.get("imageUrl")||"",fulfillmentUrl:f.get("fulfillmentUrl")||"",serviceDurationMinutes:f.get("serviceDurationMinutes")||"",eventId:f.get("eventId")||""})});const result=await response.json();if(!response.ok){setError(result.error??"Could not add product.");setBusy(false);return}router.push("/dashboard/products");router.refresh()}
  return <div className="mx-auto max-w-2xl"><Button href="/dashboard/products" tone="ghost" className="-ml-3"><ArrowLeft size={16}/>Products</Button><div className="card mt-5 p-6 sm:p-8"><p className="eyebrow text-indigo-700">New product</p><h1 className="mt-2 text-3xl font-bold tracking-tight">What are you selling?</h1><form onSubmit={submit} className="mt-7 grid gap-5"><Field label="Product type"><Select value={type} onChange={event=>setType(event.target.value)}><option value="PHYSICAL">Physical product</option><option value="FOOD">Food / preorder</option><option value="DIGITAL">Digital product</option><option value="TICKET">Ticket</option><option value="SERVICE">Service</option></Select></Field>{type==="TICKET"&&(events.length?<Field label="Event"><Select name="eventId" required><option value="">Choose an event</option>{events.map(event=><option key={event.id} value={event.id}>{event.name} · {new Date(event.startsAt).toLocaleDateString()}</option>)}</Select></Field>:<div className="rounded-[10px] bg-amber-50 p-4 text-sm text-amber-900">Create the event before adding ticket types.<Button href="/dashboard/events/new" tone="ghost" className="mt-2">Create event</Button></div>)}<Field label={type==="TICKET"?"Ticket type":"Product name"}><Input name="name" required placeholder={type==="TICKET"?"VIP admission":"Smoky Jollof + Chicken"}/></Field><Field label="Description"><Textarea name="description" required placeholder="Tell customers what they’re getting."/></Field><Field label="Default price (₦)"><Input name="price" type="number" min="1" required placeholder="5500"/></Field>{type==="DIGITAL"&&<Field label="Secure delivery URL" hint="Only paid customers will see this link."><Input name="fulfillmentUrl" type="url" placeholder="https://…"/></Field>}{type==="SERVICE"&&<Field label="Service duration (minutes)"><Input name="serviceDurationMinutes" type="number" min="1" placeholder="60"/></Field>}<Field label="Image URL" hint="Cloud image uploads will replace this field in production."><Input name="imageUrl" type="url" placeholder="https://…"/></Field>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button type="submit" disabled={busy}>{busy?"Adding product…":"Add product"}</Button></form></div></div>;
}
