import { ArrowRight, CalendarDays, MoreHorizontal, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatNaira } from "@/lib/utils";
import { requireVendor } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { effectiveWindowStatus } from "@/lib/commerce";

export default async function WindowsPage() {
  const { vendor } = await requireVendor();
  const windows = await db.sellingWindow.findMany({ where: { vendorId: vendor.id }, include: { orders: { where: { status: "PAID" }, select: { totalKobo: true } }, _count: { select: { orders: true } } }, orderBy: { createdAt: "desc" } });
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold tracking-[-.04em]">Selling windows</h1><p className="mt-2 text-slate-500">Open, close, and track every batch from one place.</p></div><Button href="/dashboard/windows/new"><Plus size={18}/>Create window</Button></div>
    <div className="hide-scrollbar flex gap-2 overflow-x-auto border-b border-slate-200">{["All","Live","Upcoming","Closed","Drafts"].map((filter,i)=><button key={filter} className={`shrink-0 border-b-2 px-3 py-3 text-sm font-semibold ${i===0?"border-indigo-700 text-indigo-700":"border-transparent text-slate-500 hover:text-slate-900"}`}>{filter}</button>)}</div>
    {windows.length===0?<div className="card p-12 text-center"><h2 className="text-xl font-bold">Your first selling window starts here.</h2><Button href="/dashboard/windows/new" className="mt-5">Create selling window</Button></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{windows.map((item)=>{const effective=effectiveWindowStatus(item);const revenue=item.orders.reduce((sum,o)=>sum+o.totalKobo,0);const timing=item.mode==="SHOP"?"Always open":effective==="LIVE"&&item.closesAt?`Closes ${item.closesAt.toLocaleString()}`:effective==="UPCOMING"&&item.opensAt?`Opens ${item.opensAt.toLocaleString()}`:item.closesAt?`Closed ${item.closesAt.toLocaleDateString()}`:"Not scheduled";return <article key={item.id} className="card group overflow-hidden transition hover:-translate-y-0.5 hover:shadow-[0_12px_30px_rgba(15,23,42,.07)]"><div className={`h-1.5 ${effective === "LIVE" ? "bg-emerald-500" : effective === "UPCOMING" ? "bg-indigo-600" : "bg-slate-200"}`}/><div className="p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-2"><Badge tone={effective === "LIVE"?"success":effective === "UPCOMING"?"indigo":"neutral"}>{effective}</Badge><Badge tone="neutral">{item.mode}</Badge></div><button className="rounded-md p-1 text-slate-400 hover:bg-slate-100" aria-label="Window options"><MoreHorizontal size={18}/></button></div><h2 className="mt-5 text-xl font-bold tracking-tight">{item.name}</h2><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><CalendarDays size={15}/>{timing}</p><div className="mt-7 grid grid-cols-2 gap-3 rounded-[10px] bg-slate-50 p-4"><div><span className="text-xs text-slate-500">Orders</span><strong className="mt-1 block">{item._count.orders}</strong></div><div><span className="text-xs text-slate-500">Revenue</span><strong className="mt-1 block">{formatNaira(revenue)}</strong></div></div><Button href={`/dashboard/windows/${item.id}/fulfillment`} tone="ghost" className="mt-4 w-full justify-between">View fulfillment<ArrowRight size={16}/></Button></div></article>})}</div>}
  </div>;
}
