"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { AuthShell } from "@/components/auth/auth-shell";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/form-field";

export default function Signup(){const[error,setError]=useState("");const[busy,setBusy]=useState(false);const router=useRouter();async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const response=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),email:data.get("email"),password:data.get("password")})});const result=await response.json();if(!response.ok){setError(result.error??"Could not create your account.");setBusy(false);return}router.push("/onboarding");router.refresh()}return <AuthShell quote="I finally know exactly how many portions to make before I enter the kitchen."><p className="eyebrow text-indigo-700">Start selling</p><h1 className="mt-3 text-4xl font-bold tracking-[-.05em]">Your next batch, sorted.</h1><p className="mt-3 text-slate-500">Create your free storefront in a few calm steps.</p><form onSubmit={submit} className="mt-8 grid gap-5"><Field label="Your name"><Input name="name" placeholder="Amaka Okafor" autoComplete="name" required/></Field><Field label="Email address"><Input name="email" type="email" placeholder="amaka@example.com" autoComplete="email" required/></Field><Field label="Password" hint="Use at least 8 characters."><Input name="password" type="password" placeholder="Create a secure password" autoComplete="new-password" minLength={8} required/></Field>{error&&<p role="alert" className="rounded-[9px] bg-red-50 p-3 text-sm font-medium text-red-700">{error}</p>}<Button type="submit" disabled={busy} size="lg" className="mt-2 w-full">{busy?"Creating your account…":"Create my account"}</Button></form><p className="mt-6 text-center text-sm text-slate-500">Already selling with us? <Link href="/login" className="font-semibold text-indigo-700">Log in</Link></p></AuthShell>}
