import assert from "node:assert/strict";
import { PrismaClient } from "@prisma/client";

const db=new PrismaClient();const base=process.env.E2E_BASE_URL||"http://127.0.0.1:3100";let productId;let windowId;let orderId;let paymentReference;
async function request(path,options={}){const response=await fetch(base+path,options);const text=await response.text();let body;try{body=JSON.parse(text)}catch{body=text}return{response,body}}
try{
  const login=await request("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:"amaka@hemigo.demo",password:"hemigo-demo"})});assert.equal(login.response.status,200);const cookie=login.response.headers.get("set-cookie")?.split(";")[0];assert.ok(cookie,"Login must set a session cookie");const authHeaders={"Content-Type":"application/json",Cookie:cookie,Origin:base};
  const marker=Date.now().toString();const createdProduct=await request("/api/dashboard/products",{method:"POST",headers:authHeaders,body:JSON.stringify({name:`E2E Product ${marker}`,description:"Created by the production smoke test",defaultPriceNaira:2500,imageUrl:""})});assert.equal(createdProduct.response.status,201);productId=createdProduct.body.product.id;
  const createdWindow=await request("/api/dashboard/windows",{method:"POST",headers:authHeaders,body:JSON.stringify({name:`E2E Window ${marker}`,description:"End-to-end test window",headline:"A real test window",opensAt:new Date(Date.now()-60_000).toISOString(),closesAt:new Date(Date.now()+3_600_000).toISOString(),theme:"CLASSIC",publish:true,products:[{productId,priceNaira:2500,inventoryLimit:2,maxPerCustomer:1}]})});assert.equal(createdWindow.response.status,201);windowId=createdWindow.body.window.id;
  const storefront=await fetch(base+createdWindow.body.shareUrl);assert.equal(storefront.status,200);
  const windowProduct=await db.windowProduct.findFirstOrThrow({where:{windowId,productId}});const reserved=await request("/api/checkout/reserve",{method:"POST",headers:{"Content-Type":"application/json",Origin:base},body:JSON.stringify({windowId,customerName:"E2E Customer",customerPhone:"08099999999",customerEmail:"e2e@example.com",fulfillmentType:"Pickup",items:[{windowProductId:windowProduct.id,quantity:1}]})});assert.equal(reserved.response.status,201);orderId=reserved.body.orderId;
  const initialized=await request("/api/payments/initialize",{method:"POST",headers:{"Content-Type":"application/json",Origin:base},body:JSON.stringify({orderId})});assert.equal(initialized.response.status,200);paymentReference=initialized.body.reference;assert.match(initialized.body.authorization_url,/^\/order\//);
  const success=await fetch(base+initialized.body.authorization_url);assert.equal(success.status,200);const order=await db.order.findUniqueOrThrow({where:{id:orderId}});assert.equal(order.status,"PAID");console.log("E2E PASS: auth → product → window → storefront → reservation → payment → paid order");
}finally{if(paymentReference)await db.settlement.deleteMany({where:{providerReference:paymentReference}});if(orderId){await db.payment.deleteMany({where:{orderId}});await db.orderItem.deleteMany({where:{orderId}});await db.order.deleteMany({where:{id:orderId}})}if(windowId){await db.windowProduct.deleteMany({where:{windowId}});await db.sellingWindow.deleteMany({where:{id:windowId}})}if(productId)await db.product.deleteMany({where:{id:productId}});await db.$disconnect()}
