import { ArrowDownLeft, Building2, CheckCircle2, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { requireVendor } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { formatNaira } from "@/lib/utils";

export default async function PayoutsPage() {
  const { vendor }=await requireVendor();const settlements=await db.settlement.findMany({where:{vendorId:vendor.id},orderBy:{createdAt:"desc"}});const paid=settlements.filter(s=>s.status==="PAID").reduce((sum,s)=>sum+s.netKobo,0);const pending=settlements.filter(s=>s.status==="PENDING"||s.status==="PROCESSING").reduce((sum,s)=>sum+s.netKobo,0);
  return <div className="space-y-7"><div><h1 className="text-3xl font-bold tracking-[-.04em]">Payouts</h1><p className="mt-2 text-slate-500">Your earnings, fees, and settlement history.</p></div><section className="overflow-hidden rounded-[16px] bg-slate-950 p-6 text-white sm:p-8"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-sm text-slate-400">Pending balance</p><h2 className="mt-3 text-4xl font-bold">{formatNaira(pending)}</h2><Badge tone="dark" className="mt-5">PAYSTACK SETTLEMENT</Badge></div><div className="rounded-[12px] bg-white/8 p-5"><div className="flex items-center gap-3"><Building2/><div><p className="font-semibold">{vendor.bankName||"Bank setup pending"}</p><p className="text-xs text-slate-400">{vendor.accountNumber?`•••• ${vendor.accountNumber.slice(-4)} · ${vendor.accountName}`:"Complete payout settings"}</p></div>{vendor.accountNumber&&<CheckCircle2 className="ml-auto text-emerald-400"/>}</div></div></div></section><div className="card p-5"><WalletCards className="text-indigo-700"/><p className="mt-4 text-2xl font-bold">{formatNaira(paid)}</p><p className="text-sm text-slate-500">Paid out to date</p></div><section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Settlement history</h2></div>{settlements.length?settlements.map(item=><div key={item.id} className="flex items-center gap-4 border-b p-5"><ArrowDownLeft className="text-emerald-700"/><div className="flex-1"><p className="font-semibold">{item.status}</p><p className="text-xs text-slate-500">{item.settledAt?.toLocaleDateString()||item.createdAt.toLocaleDateString()}</p></div><strong>{formatNaira(item.netKobo)}</strong></div>):<p className="p-8 text-center text-slate-500">Settlements will appear after live payments.</p>}</section></div>;
}
