"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, ExternalLink, Package, Smartphone, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, Input, Textarea } from "@/components/ui/form-field";
import { foodProducts } from "@/lib/demo-data";
import { formatNaira } from "@/lib/utils";

const labels = ["Window details", "Add products", "Preview & publish"];

export default function NewWindow() {
  const [step, setStep] = useState(0);
  const [published, setPublished] = useState(false);
  if (published) return <div className="mx-auto max-w-2xl py-10"><div className="card overflow-hidden text-center"><div className="bg-indigo-700 px-8 py-12 text-white"><span className="mx-auto grid size-16 place-items-center rounded-full bg-white/15"><CheckCircle2 size={34}/></span><h1 className="mt-5 text-3xl font-bold tracking-tight">Your selling window is live 🎉</h1><p className="mt-3 text-indigo-100">Sunday Lunch Batch is ready for customers.</p></div><div className="p-7"><p className="text-sm font-semibold text-slate-500">YOUR SHARE LINK</p><div className="mt-3 rounded-[10px] border border-slate-200 bg-slate-50 p-4 font-semibold text-indigo-700">hemigo.ng/amaka-kitchen/sunday-lunch</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Button tone="secondary">Copy link</Button><Button className="bg-[#25D366] border-[#25D366] hover:bg-[#1dbf59]">Share on WhatsApp</Button></div><Button href="/amaka-kitchen/sunday-lunch" tone="ghost" className="mt-5">Open storefront <ExternalLink size={16}/></Button></div></div></div>;
  return <div className="mx-auto max-w-5xl"><div className="mb-8"><button onClick={()=>step>0&&setStep(step-1)} className="mb-5 flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={17}/>Back</button><h1 className="text-3xl font-bold tracking-[-.04em]">Create a selling window</h1><p className="mt-2 text-slate-500">Set the rules once. Hemigo handles the rush.</p></div>
    <div className="mb-7 grid grid-cols-3 gap-2">{labels.map((label,i)=><div key={label}><div className={`h-1.5 rounded-full ${i<=step?"bg-indigo-600":"bg-slate-200"}`}/><p className={`mt-2 text-xs font-semibold ${i===step?"text-indigo-700":"text-slate-400"}`}>{i+1}. <span className="hidden sm:inline">{label}</span></p></div>)}</div>
    {step===0&&<div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="card p-6 sm:p-8"><div className="grid gap-5"><Field label="Window name"><Input defaultValue="Sunday Lunch Batch"/></Field><Field label="Description" hint="Tell customers what makes this batch worth claiming."><Textarea defaultValue="A proper Sunday spread, freshly made and ready for pickup or delivery."/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Orders open"><Input type="datetime-local" defaultValue="2026-09-19T08:00"/></Field><Field label="Orders close"><Input type="datetime-local" defaultValue="2026-09-20T08:00"/></Field></div><Field label="Fulfillment date (optional)"><Input type="date" defaultValue="2026-09-20"/></Field><div><p className="mb-3 text-sm font-semibold text-slate-700">Storefront theme</p><div className="grid gap-3 sm:grid-cols-2"><label className="cursor-pointer rounded-[12px] border-2 border-indigo-600 bg-indigo-50 p-4"><input type="radio" name="theme" defaultChecked className="sr-only"/><span className="flex items-center gap-3 font-bold"><span className="grid size-9 place-items-center rounded-lg bg-white text-indigo-700"><Smartphone size={17}/></span>Classic <Check className="ml-auto text-indigo-700" size={17}/></span><span className="mt-2 block text-xs text-slate-500">Bright, warm and product-led.</span></label><label className="cursor-pointer rounded-[12px] border border-slate-200 bg-zinc-900 p-4 text-white"><input type="radio" name="theme" className="sr-only"/><span className="flex items-center gap-3 font-bold"><span className="grid size-9 place-items-center rounded-lg bg-zinc-800 text-lime-300"><Sparkles size={17}/></span>Hype</span><span className="mt-2 block text-xs text-zinc-400">Dark, energetic and limited.</span></label></div></div></div></section><aside className="rounded-[16px] bg-indigo-700 p-6 text-white"><Clock3 className="text-amber-300"/><h2 className="mt-5 text-2xl font-bold">A clear deadline changes everything.</h2><p className="mt-4 text-sm leading-7 text-indigo-100">Once this window closes, checkout stops automatically. Existing reservations still get their 8 minutes to pay.</p><div className="mt-8 rounded-[12px] bg-white/10 p-4"><p className="text-xs text-indigo-200">CUSTOMERS WILL SEE</p><p className="mt-3 text-sm">Orders close in</p><p className="mt-1 text-3xl font-bold text-amber-300">23 : 42 : 18</p></div></aside></div>}
    {step===1&&<section className="card overflow-hidden"><div className="border-b border-slate-200 p-6 sm:p-8"><h2 className="text-2xl font-bold">What are you selling?</h2><p className="mt-2 text-sm text-slate-500">Choose products and set stock for this window.</p></div><div className="divide-y divide-slate-100">{foodProducts.slice(0,3).map((product,i)=><div key={product.id} className="grid items-center gap-4 p-5 sm:grid-cols-[auto_1fr_.7fr_.7fr]"><input type="checkbox" defaultChecked className="size-5 accent-indigo-700" aria-label={`Select ${product.name}`}/><div><p className="font-bold">{product.name}</p><p className="text-sm text-slate-500">Default: {formatNaira(product.priceKobo)}</p></div><Field label="Window price"><Input defaultValue={(product.priceKobo/100).toString()}/></Field><Field label="Quantity available"><Input type="number" defaultValue={i===0?50:i===1?36:45}/></Field></div>)}</div><div className="border-t border-slate-200 bg-slate-50 p-5 text-sm text-slate-600"><Package className="mr-2 inline text-indigo-700" size={17}/>3 products selected · 131 total units</div></section>}
    {step===2&&<div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="card p-6"><p className="eyebrow text-indigo-700">Ready to publish</p><h2 className="mt-3 text-2xl font-bold">Sunday Lunch Batch</h2><div className="mt-6 space-y-4 border-y border-slate-100 py-5 text-sm">{[["Opens","Saturday · 8:00 AM"],["Closes","Sunday · 8:00 AM"],["Products","3"],["Total units","131"]].map(([k,v])=><div key={k} className="flex justify-between"><span className="text-slate-500">{k}</span><strong>{v}</strong></div>)}</div><div className="mt-5 flex items-center gap-2 text-sm text-emerald-700"><CheckCircle2 size={17}/>Inventory checks are ready</div></section><section className="overflow-hidden rounded-[16px] bg-[#fffaf0] shadow-[0_16px_50px_rgba(15,23,42,.08)]"><div className="relative h-48 bg-[url('https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1000&q=85')] bg-cover bg-center"><span className="absolute left-5 top-5 rounded-full bg-white/95 px-3 py-1.5 text-xs font-extrabold">AMAKA&apos;S KITCHEN</span></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-amber-700">Orders close in 23:42:18</p><h3 className="mt-2 text-2xl font-bold">Sunday tastes better here.</h3><p className="mt-2 text-sm text-slate-600">3 delicious options, made fresh for Sunday.</p></div></section></div>}
    <div className="mt-7 flex justify-end"><Button onClick={()=>step<2?setStep(step+1):setPublished(true)}>{step<2?"Continue":"Publish selling window"}<ArrowRight size={17}/></Button></div>
  </div>;
}
