"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, ExternalLink, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, Input, Textarea } from "@/components/ui/form-field";
import { formatNaira } from "@/lib/utils";

type DbProduct={id:string;name:string;defaultPrice:number};
type Selection={productId:string;selected:boolean;priceNaira:number;inventoryLimit:number;maxPerCustomer:number};

export default function NewWindow(){
  const[step,setStep]=useState(0);const[products,setProducts]=useState<DbProduct[]>([]);const[selections,setSelections]=useState<Record<string,Selection>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[result,setResult]=useState<{shareUrl:string}|null>(null);
  const now=new Date();const tomorrow=new Date(now.getTime()+86_400_000);const dayAfter=new Date(now.getTime()+172_800_000);
  const local=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,16);
  const[details,setDetails]=useState({name:"",description:"",headline:"",opensAt:local(tomorrow),closesAt:local(dayAfter),fulfillmentAt:local(new Date(dayAfter.getTime()+6*3_600_000)),theme:"CLASSIC"});
  useEffect(()=>{fetch("/api/dashboard/products").then(r=>r.json()).then(({products})=>{setProducts(products);setSelections(Object.fromEntries(products.map((p:DbProduct)=>[p.id,{productId:p.id,selected:false,priceNaira:p.defaultPrice/100,inventoryLimit:20,maxPerCustomer:5}])))});},[]);
  const selected=Object.values(selections).filter(s=>s.selected);
  const updateSelection=(id:string,patch:Partial<Selection>)=>setSelections(current=>({...current,[id]:{...current[id],...patch}}));
  async function publish(){setBusy(true);setError("");const response=await fetch("/api/dashboard/windows",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...details,publish:true,products:selected.map(({productId,priceNaira,inventoryLimit,maxPerCustomer})=>({productId,priceNaira,inventoryLimit,maxPerCustomer}))})});const body=await response.json();if(!response.ok){setError(body.error??"Could not publish this window.");setBusy(false);return}setResult(body)}
  if(result)return <div className="mx-auto max-w-2xl py-10"><div className="card overflow-hidden text-center"><div className="bg-indigo-700 px-8 py-12 text-white"><CheckCircle2 className="mx-auto" size={52}/><h1 className="mt-5 text-3xl font-bold">Your selling window is live 🎉</h1></div><div className="p-7"><p className="rounded-[10px] bg-slate-50 p-4 font-semibold text-indigo-700">{location.origin}{result.shareUrl}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Button tone="secondary" onClick={()=>navigator.clipboard.writeText(location.origin+result.shareUrl)}>Copy link</Button><Button onClick={()=>window.open(`https://wa.me/?text=${encodeURIComponent(location.origin+result.shareUrl)}`)}>Share on WhatsApp</Button></div><Button href={result.shareUrl} tone="ghost" className="mt-4">Open storefront <ExternalLink size={16}/></Button></div></div></div>;
  return <div className="mx-auto max-w-5xl"><button onClick={()=>step?setStep(step-1):history.back()} className="mb-5 flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={17}/>Back</button><h1 className="text-3xl font-bold tracking-tight">Create a selling window</h1><p className="mt-2 text-slate-500">Set the rules once. Hemigo handles the rush.</p><div className="my-7 grid grid-cols-3 gap-2">{["Window details","Add products","Preview & publish"].map((label,i)=><div key={label}><div className={`h-1.5 rounded-full ${i<=step?"bg-indigo-600":"bg-slate-200"}`}/><p className="mt-2 text-xs font-semibold text-slate-500">{i+1}. {label}</p></div>)}</div>
  {step===0&&<section className="card grid gap-5 p-6 sm:p-8"><Field label="Window name"><Input value={details.name} onChange={e=>setDetails({...details,name:e.target.value})} placeholder="Sunday Lunch Batch"/></Field><Field label="Description"><Textarea value={details.description} onChange={e=>setDetails({...details,description:e.target.value})}/></Field><Field label="Storefront headline"><Input value={details.headline} onChange={e=>setDetails({...details,headline:e.target.value})} placeholder="Sunday tastes better here."/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Orders open"><Input type="datetime-local" value={details.opensAt} onChange={e=>setDetails({...details,opensAt:e.target.value})}/></Field><Field label="Orders close"><Input type="datetime-local" value={details.closesAt} onChange={e=>setDetails({...details,closesAt:e.target.value})}/></Field></div><Field label="Fulfillment time"><Input type="datetime-local" value={details.fulfillmentAt} onChange={e=>setDetails({...details,fulfillmentAt:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3">{["CLASSIC","HYPE"].map(theme=><button key={theme} onClick={()=>setDetails({...details,theme})} className={`rounded-[12px] border p-5 text-left ${details.theme===theme?"border-indigo-600 bg-indigo-50":"border-slate-200"}`}><Sparkles size={18}/><strong className="mt-4 block">{theme[0]+theme.slice(1).toLowerCase()}</strong></button>)}</div></section>}
  {step===1&&<section className="card overflow-hidden"><div className="p-6"><h2 className="text-2xl font-bold">What are you selling?</h2></div>{products.length===0?<div className="border-t p-8 text-center"><p className="text-slate-500">Add a product before creating a window.</p><Button href="/dashboard/products/new" className="mt-4">Add product</Button></div>:<div className="divide-y">{products.map(product=>{const s=selections[product.id];if(!s)return null;return <div key={product.id} className="grid gap-4 p-5 sm:grid-cols-[auto_1fr_1fr_1fr]"><input type="checkbox" checked={s.selected} onChange={e=>updateSelection(product.id,{selected:e.target.checked})} className="size-5 accent-indigo-700"/><div><strong>{product.name}</strong><p className="text-sm text-slate-500">{formatNaira(product.defaultPrice)}</p></div><Field label="Price (₦)"><Input type="number" value={s.priceNaira} onChange={e=>updateSelection(product.id,{priceNaira:Number(e.target.value)})}/></Field><Field label="Available"><Input type="number" value={s.inventoryLimit} onChange={e=>updateSelection(product.id,{inventoryLimit:Number(e.target.value)})}/></Field></div>})}</div>}</section>}
  {step===2&&<div className="grid gap-5 lg:grid-cols-2"><section className="card p-6"><p className="eyebrow text-indigo-700">Ready to publish</p><h2 className="mt-3 text-2xl font-bold">{details.name||"Untitled window"}</h2><div className="mt-6 space-y-3 border-y py-5 text-sm"><p className="flex justify-between"><span>Opens</span><strong>{new Date(details.opensAt).toLocaleString()}</strong></p><p className="flex justify-between"><span>Closes</span><strong>{new Date(details.closesAt).toLocaleString()}</strong></p><p className="flex justify-between"><span>Products</span><strong>{selected.length}</strong></p></div></section><section className={`rounded-[16px] p-7 ${details.theme==="HYPE"?"bg-zinc-900 text-white":"bg-amber-50"}`}><p className="eyebrow text-amber-600">Orders open soon</p><h3 className="mt-4 text-3xl font-bold">{details.headline||details.name}</h3><p className="mt-3 opacity-70">{details.description}</p></section></div>}
  {error&&<p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-7 flex justify-end"><Button disabled={(step===1&&!selected.length)||busy} onClick={()=>step<2?setStep(step+1):publish()}>{step<2?"Continue":busy?"Publishing…":"Publish selling window"}<ArrowRight size={17}/></Button></div></div>;
}
