import { ArrowRight, Banknote, ExternalLink, PackageCheck, Plus, ReceiptText, Store } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Countdown } from "@/components/countdown";
import { StatCard } from "@/components/dashboard/stat-card";
import { OrdersTable } from "@/components/dashboard/orders-table";

export default function Dashboard() {
  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-indigo-700">Thursday, 17 September</p><h1 className="mt-2 text-3xl font-bold tracking-[-.04em] sm:text-4xl">Good morning, Amaka.</h1><p className="mt-2 text-slate-500">Here&apos;s what&apos;s happening with your store.</p></div><Button href="/dashboard/windows/new"><Plus size={18}/>New selling window</Button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Sales this month" value="₦482,500" note="↑ 18.4% from August" icon={Banknote}/><StatCard label="Orders" value="126" note="18 new this week" icon={ReceiptText}/><StatCard label="Selling windows" value="4" note="1 live · 1 upcoming" icon={Store}/><StatCard label="Payouts" value="₦463,200" note="Last payout 15 Sep" icon={PackageCheck}/></div>
    <section className="overflow-hidden rounded-[16px] border border-indigo-200 bg-indigo-700 text-white shadow-[0_18px_50px_rgba(67,56,202,.14)]"><div className="grid lg:grid-cols-[1fr_.75fr]"><div className="p-6 sm:p-8"><div className="flex items-center gap-2"><span className="live-dot size-2 rounded-full bg-emerald-400"/><span className="eyebrow text-indigo-100">Active window</span></div><h2 className="mt-5 text-3xl font-bold tracking-tight">Sunday Lunch Batch</h2><p className="mt-2 max-w-lg text-sm leading-6 text-indigo-100">Your customers are claiming lunch. Everything is running on schedule.</p><div className="mt-8 flex flex-wrap gap-x-8 gap-y-4"><div><p className="text-xs text-indigo-200">Orders</p><strong className="mt-1 block text-xl">42</strong></div><div><p className="text-xs text-indigo-200">Revenue</p><strong className="mt-1 block text-xl">₦286,500</strong></div><div><p className="text-xs text-indigo-200">Units claimed</p><strong className="mt-1 block text-xl">128</strong></div></div></div><div className="border-t border-white/10 bg-indigo-800/50 p-6 sm:p-8 lg:border-l lg:border-t-0"><p className="eyebrow text-amber-300">Orders close in</p><div className="mt-4"><Countdown/></div><p className="mt-3 text-xs text-indigo-200">Sunday at 8:00 AM</p><div className="mt-7 flex flex-wrap gap-2"><Button href="/dashboard/orders" tone="secondary" size="sm">View orders <ArrowRight size={15}/></Button><Button href="/amaka-kitchen/sunday-lunch" tone="ghost" size="sm" className="text-white hover:bg-white/10">Open storefront <ExternalLink size={14}/></Button></div></div></div></section>
    <section className="card overflow-hidden"><div className="flex items-center justify-between p-5 sm:px-6"><div><h2 className="text-lg font-bold">Recent orders</h2><p className="mt-1 text-sm text-slate-500">The latest activity across your windows.</p></div><Button href="/dashboard/orders" tone="ghost" size="sm">View all <ArrowRight size={16}/></Button></div><OrdersTable limit={5}/></section>
    <div className="grid gap-4 lg:grid-cols-2"><section className="card p-6"><div className="flex items-center justify-between"><div><p className="eyebrow text-indigo-700">Next up</p><h3 className="mt-2 text-xl font-bold">Friday Cake Batch</h3></div><Badge tone="indigo">UPCOMING</Badge></div><p className="mt-4 text-sm text-slate-500">Opens tomorrow at 9:00 AM · 3 products</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-2/3 bg-indigo-600"/></div><p className="mt-2 text-xs text-slate-500">Storefront ready to publish</p></section><section className="card p-6"><p className="eyebrow text-emerald-700">Payout on the way</p><div className="mt-3 flex items-end justify-between"><div><h3 className="text-2xl font-bold">₦124,200</h3><p className="mt-1 text-sm text-slate-500">Expected Friday, 18 September</p></div><Badge tone="success">Processing</Badge></div><div className="mt-6 border-t border-slate-100 pt-4 text-xs text-slate-500">Sunday Lunch Batch · Paystack split settlement</div></section></div>
  </div>;
}
