"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, MapPin, Minus, Plus, ShieldCheck, ShoppingBag, X } from "lucide-react";
import { Countdown } from "@/components/countdown";
import { Badge } from "@/components/ui/badge";
import { cn, formatNaira } from "@/lib/utils";

export type StorefrontData={windowId:string;vendorName:string;vendorSlug:string;windowName:string;windowSlug:string;headline:string;description:string;location:string|null;closesAt:string;theme:"CLASSIC"|"HYPE";isOpen:boolean;products:Array<{id:string;name:string;description:string;priceKobo:number;image:string;inventory:number|null;sold:number;reserved:number;maxPerCustomer:number|null}>};

export function Storefront({data}:{data:StorefrontData}){
  const hype=data.theme==="HYPE";const[quantities,setQuantities]=useState<Record<string,number>>({});const[bagOpen,setBagOpen]=useState(false);
  useEffect(()=>{const saved=localStorage.getItem(`hemigo_cart_${data.windowId}`);if(saved)try{setQuantities(JSON.parse(saved))}catch{}},[data.windowId]);
  useEffect(()=>{localStorage.setItem(`hemigo_cart_${data.windowId}`,JSON.stringify(quantities))},[data.windowId,quantities]);
  const count=Object.values(quantities).reduce((a,b)=>a+b,0);const total=data.products.reduce((sum,p)=>sum+(quantities[p.id]??0)*p.priceKobo,0);const selected=useMemo(()=>data.products.filter(p=>quantities[p.id]),[data.products,quantities]);
  const update=(product:StorefrontData["products"][number],amount:number)=>setQuantities(current=>{const available=product.inventory===null?50:Math.max(0,product.inventory-product.sold-product.reserved);const next=Math.min(product.maxPerCustomer??50,available,Math.max(0,(current[product.id]??0)+amount));return{...current,[product.id]:next}});
  return <main className={cn("min-h-screen pb-28",hype?"bg-zinc-950 text-white":"bg-[#fffcf5]")}><header className={cn("sticky top-0 z-30 border-b backdrop-blur-xl",hype?"border-zinc-800 bg-zinc-950/90":"border-amber-100 bg-[#fffcf5]/90")}><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><Link href="/" className={cn("flex items-center gap-2 text-sm font-extrabold tracking-wider",hype?"text-lime-300":"text-indigo-700")}><span className={cn("grid size-8 place-items-center rounded-[9px]",hype?"bg-lime-300 text-zinc-950":"bg-indigo-700 text-white")}>H</span>{data.vendorName.toUpperCase()}</Link><button onClick={()=>setBagOpen(true)} className={cn("relative grid size-10 place-items-center rounded-[10px] border",hype?"border-zinc-700":"border-slate-200 bg-white")}><ShoppingBag size={19}/>{count>0&&<span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-emerald-500 text-[10px] font-bold text-white">{count}</span>}</button></div></header>
  <section className={cn("overflow-hidden",hype?"bg-zinc-900":"bg-amber-50")}><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 py-14 lg:grid-cols-[1fr_.85fr]"><div><div className="flex items-center gap-2"><Badge tone={data.isOpen?(hype?"dark":"success"):"neutral"}>{data.isOpen?"ORDERS OPEN":"ORDERS CLOSED"}</Badge>{data.location&&<span className="flex items-center gap-1 text-xs opacity-60"><MapPin size={13}/>{data.location}</span>}</div><p className={cn("eyebrow mt-7",hype?"text-zinc-400":"text-amber-700")}>{data.windowName}</p><h1 className="mt-3 max-w-2xl text-5xl font-bold leading-[.96] tracking-[-.055em] sm:text-6xl">{data.headline}</h1><p className="mt-5 max-w-xl leading-7 opacity-65">{data.description}</p></div><div className={cn("rounded-[18px] border p-6",hype?"border-zinc-700 bg-zinc-950":"border-amber-200 bg-white")}><p className="eyebrow text-amber-600">{data.isOpen?"Orders close in":"This selling window has closed"}</p><div className="mt-4">{data.isOpen?<Countdown target={data.closesAt} dark={hype}/>:<p className="text-lg font-bold">Orders are closed.</p>}</div><p className="mt-4 text-xs opacity-55">{new Date(data.closesAt).toLocaleString()}</p><div className="mt-6 flex items-center gap-2 border-t border-current/10 pt-5 text-xs opacity-60"><ShieldCheck size={16} className="text-emerald-500"/>Secure checkout powered by Paystack</div></div></div></section>
  <section className="mx-auto max-w-6xl px-4 py-14"><p className={cn("eyebrow",hype?"text-lime-300":"text-indigo-700")}>{hype?"THE DROP":"AVAILABLE NOW"}</p><h2 className="mt-2 text-3xl font-bold">Choose your favourites</h2><div className="mt-8 grid gap-5 sm:grid-cols-2">{data.products.map(product=>{const q=quantities[product.id]??0;const left=product.inventory===null?null:Math.max(0,product.inventory-product.sold-product.reserved);return <article key={product.id} className={cn("overflow-hidden rounded-[16px] border",hype?"border-zinc-800 bg-zinc-900":"border-slate-200 bg-white")}><div className="relative aspect-[4/3]"><Image src={product.image} alt={product.name} fill sizes="(max-width:640px) 100vw, 50vw" className="object-cover"/>{left!==null&&left<=8&&left>0&&<span className="absolute left-4 top-4 rounded-full bg-amber-400 px-3 py-1.5 text-[11px] font-extrabold text-amber-950">ONLY {left} LEFT</span>}</div><div className="p-5"><h3 className="text-xl font-bold">{product.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 opacity-60">{product.description}</p><div className="mt-5 flex items-center justify-between"><strong className="text-xl">{formatNaira(product.priceKobo)}</strong>{!data.isOpen||left===0?<span className="text-sm font-bold opacity-50">All claimed</span>:q===0?<button onClick={()=>update(product,1)} className={cn("h-10 rounded-[10px] px-4 text-sm font-bold",hype?"bg-lime-300 text-zinc-950":"bg-emerald-500 text-white")}><Plus className="mr-1 inline" size={16}/>Add to bag</button>:<div className="flex items-center gap-3 rounded-[10px] border border-current/20 p-2"><button onClick={()=>update(product,-1)}><Minus size={15}/></button><strong>{q}</strong><button onClick={()=>update(product,1)}><Plus size={15}/></button></div>}</div></div></article>})}</div></section>
  {count>0&&<button onClick={()=>setBagOpen(true)} className={cn("fixed bottom-3 left-1/2 z-30 flex h-16 w-[calc(100%-24px)] max-w-xl -translate-x-1/2 items-center rounded-[14px] px-4 font-semibold shadow-2xl",hype?"bg-lime-300 text-zinc-950":"bg-emerald-500 text-white")}><span>{count} items</span><span className="ml-auto">{formatNaira(total)}</span><ArrowRight className="ml-2" size={18}/></button>}
  {bagOpen&&<><button className="fixed inset-0 z-40 bg-slate-950/50" onClick={()=>setBagOpen(false)}/><aside className={cn("fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col",hype?"bg-zinc-950":"bg-white")}><div className="flex items-center justify-between border-b border-current/10 p-5"><h2 className="text-xl font-bold">Your bag</h2><button onClick={()=>setBagOpen(false)}><X/></button></div><div className="flex-1 space-y-4 overflow-auto p-5">{selected.map(product=><div key={product.id} className="flex gap-3 rounded-xl border border-current/10 p-3"><Image src={product.image} alt="" width={72} height={72} className="size-18 rounded-lg object-cover"/><div className="flex-1"><strong>{product.name}</strong><p className="mt-1 text-sm opacity-60">{formatNaira(product.priceKobo)}</p><div className="mt-2 flex gap-3"><button onClick={()=>update(product,-1)}><Minus size={15}/></button><strong>{quantities[product.id]}</strong><button onClick={()=>update(product,1)}><Plus size={15}/></button></div></div></div>)}</div><div className="border-t border-current/10 p-5"><div className="flex justify-between text-xl font-bold"><span>Total</span><span>{formatNaira(total)}</span></div><Link href={`/checkout/${data.windowId}`} className={cn("mt-5 flex h-13 items-center justify-center rounded-[10px] font-bold",hype?"bg-lime-300 text-zinc-950":"bg-emerald-500 text-white")}>Continue to checkout <ArrowRight className="ml-2" size={18}/></Link></div></aside></>}
  </main>;
}
