"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, MapPin, Minus, Plus, ShieldCheck, ShoppingBag, X } from "lucide-react";
import { Countdown } from "@/components/countdown";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { fashionProducts, foodProducts } from "@/lib/demo-data";
import { cn, formatNaira } from "@/lib/utils";

export function Storefront({ hype = false }: { hype?: boolean }) {
  const products = hype ? fashionProducts : foodProducts;
  const [quantities, setQuantities] = useState<Record<string, number>>({});
  const [bagOpen, setBagOpen] = useState(false);
  const count = Object.values(quantities).reduce((a,b)=>a+b,0);
  const total = products.reduce((sum,p)=>sum+(quantities[p.id]??0)*p.priceKobo,0);
  const update = (id:string, amount:number) => setQuantities(q=>({...q,[id]:Math.max(0,(q[id]??0)+amount)}));
  const selected = useMemo(()=>products.filter(p=>quantities[p.id]),[products,quantities]);
  return <main className={cn("min-h-screen pb-28",hype?"bg-zinc-950 text-white":"bg-[#fffcf5] text-slate-950")}>
    <header className={cn("sticky top-0 z-30 border-b backdrop-blur-xl",hype?"border-zinc-800 bg-zinc-950/90":"border-amber-100 bg-[#fffcf5]/90")}><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><Link href="/" className={cn("flex items-center gap-2 text-sm font-extrabold tracking-wider",hype?"text-lime-300":"text-indigo-700")}><span className={cn("grid size-8 place-items-center rounded-[9px]",hype?"bg-lime-300 text-zinc-950":"bg-indigo-700 text-white")}>H</span>{hype?"NOIR LAGOS":"AMAKA’S KITCHEN"}</Link><button onClick={()=>setBagOpen(true)} className={cn("relative grid size-10 place-items-center rounded-[10px] border",hype?"border-zinc-700 bg-zinc-900":"border-slate-200 bg-white")} aria-label={`Open bag with ${count} items`}><ShoppingBag size={19}/>{count>0&&<span className="absolute -right-1.5 -top-1.5 grid size-5 place-items-center rounded-full bg-emerald-500 text-[10px] font-bold text-white">{count}</span>}</button></div></header>
    <section className={cn("relative overflow-hidden",hype?"bg-zinc-900":"bg-amber-50")}><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[1fr_.85fr] lg:py-20"><div className="relative z-10"><div className="flex items-center gap-2"><Badge tone={hype?"dark":"success"}><span className="mr-1.5 size-1.5 rounded-full bg-current"/>ORDERS OPEN</Badge>{!hype&&<span className="flex items-center gap-1 text-xs text-slate-500"><MapPin size={13}/>Lekki, Lagos</span>}</div><p className={cn("eyebrow mt-7",hype?"text-zinc-400":"text-amber-700")}>{hype?"SEPTEMBER RELEASE":"SUNDAY LUNCH BATCH"}</p><h1 className={cn("mt-3 max-w-2xl text-5xl font-bold leading-[.96] tracking-[-.055em] sm:text-6xl",hype?"text-white":"text-slate-950")}>{hype?"Old pieces. New energy.":"Sunday tastes better here."}</h1><p className={cn("mt-5 max-w-xl text-base leading-7",hype?"text-zinc-400":"text-slate-600")}>{hype?"Rare vintage and considered essentials. Once a piece is claimed, it’s gone.":"Smoky rice, juicy chicken, and the sides that make Sunday feel like Sunday. Made fresh in Lagos."}</p></div><div className={cn("relative overflow-hidden rounded-[18px] border p-6",hype?"border-zinc-700 bg-zinc-950":"border-amber-200 bg-white")}><div className={cn("absolute right-[-50px] top-[-50px] size-40 rounded-full",hype?"bg-lime-300/10":"bg-amber-100")}/><p className={cn("eyebrow",hype?"text-zinc-400":"text-amber-700")}>Orders close in</p><div className="mt-4"><Countdown dark={hype}/></div><p className={cn("mt-4 text-xs",hype?"text-zinc-500":"text-slate-500")}>{hype?"Friday · 10:00 PM":"Sunday · 8:00 AM"}</p><div className={cn("mt-6 flex items-center gap-2 border-t pt-5 text-xs",hype?"border-zinc-800 text-zinc-400":"border-slate-100 text-slate-500")}><ShieldCheck size={16} className="text-emerald-500"/>Secure checkout powered by Paystack</div></div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><div className="flex items-end justify-between"><div><p className={cn("eyebrow",hype?"text-lime-300":"text-indigo-700")}>{hype?"THE DROP":"ON THE MENU"}</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Choose your favourites</h2></div><p className={cn("hidden text-sm sm:block",hype?"text-zinc-500":"text-slate-500")}>{products.length} items available</p></div><div className="mt-8 grid gap-5 sm:grid-cols-2">{products.map((product)=>{const q=quantities[product.id]??0;const left=(product.inventory??99)-product.sold;return <article key={product.id} className={cn("overflow-hidden rounded-[16px] border",hype?"border-zinc-800 bg-zinc-900":"border-slate-200 bg-white")}><div className="relative aspect-[4/3] overflow-hidden"><Image src={product.image} alt={product.name} fill sizes="(max-width: 640px) 100vw, 50vw" className="object-cover transition duration-500 hover:scale-[1.03]"/>{left<=8&&<span className={cn("absolute left-4 top-4 rounded-full px-3 py-1.5 text-[11px] font-extrabold",hype?"bg-lime-300 text-zinc-950":"bg-amber-400 text-amber-950")}>{hype?"ONE OF FEW":"ONLY "+left+" LEFT"}</span>}</div><div className="p-5 sm:p-6"><h3 className="text-xl font-bold tracking-tight">{product.name}</h3><p className={cn("mt-2 min-h-12 text-sm leading-6",hype?"text-zinc-400":"text-slate-500")}>{product.description}</p><div className="mt-5 flex items-center justify-between"><strong className="text-xl">{formatNaira(product.priceKobo)}</strong>{q===0?<button onClick={()=>update(product.id,1)} className={cn("focus-ring flex h-10 items-center gap-2 rounded-[10px] px-4 text-sm font-bold transition",hype?"bg-lime-300 text-zinc-950 hover:bg-lime-200":"bg-emerald-500 text-white hover:bg-emerald-600")}><Plus size={16}/>Add to bag</button>:<div className={cn("flex items-center rounded-[10px] border p-1",hype?"border-zinc-700":"border-slate-200")}><button onClick={()=>update(product.id,-1)} className="grid size-8 place-items-center rounded-md" aria-label={`Remove one ${product.name}`}><Minus size={15}/></button><span className="w-8 text-center text-sm font-bold">{q}</span><button onClick={()=>update(product.id,1)} className="grid size-8 place-items-center rounded-md" aria-label={`Add one ${product.name}`}><Plus size={15}/></button></div>}</div></div></article>})}</div></section>
    {count>0&&<div className="fixed inset-x-0 bottom-0 z-30 p-3"><button onClick={()=>setBagOpen(true)} className={cn("mx-auto flex h-16 w-full max-w-xl items-center rounded-[14px] px-4 text-left font-semibold text-white shadow-[0_16px_40px_rgba(15,23,42,.25)]",hype?"bg-lime-300 text-zinc-950":"bg-emerald-500")}><span className={cn("grid size-9 place-items-center rounded-[9px] text-sm",hype?"bg-zinc-950 text-white":"bg-white/18")}>{count}</span><span className="ml-3">View bag</span><span className="ml-auto font-bold">{formatNaira(total)}</span><ArrowRight className="ml-2" size={18}/></button></div>}
    {bagOpen&&<><button className="fixed inset-0 z-40 bg-slate-950/50 backdrop-blur-sm" onClick={()=>setBagOpen(false)} aria-label="Close bag overlay"/><aside className={cn("fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col shadow-2xl",hype?"bg-zinc-950 text-white":"bg-white")}><div className={cn("flex items-center justify-between border-b p-5",hype?"border-zinc-800":"border-slate-200")}><div><p className="eyebrow opacity-60">Your bag</p><h2 className="mt-1 text-xl font-bold">{count} {count===1?"item":"items"}</h2></div><button onClick={()=>setBagOpen(false)} className="rounded-lg p-2" aria-label="Close bag"><X/></button></div><div className="flex-1 overflow-y-auto p-5">{selected.length===0?<div className="grid h-full place-items-center text-center"><div><ShoppingBag className="mx-auto opacity-30" size={40}/><p className="mt-4 font-bold">Your bag is waiting.</p></div></div>:<div className="space-y-4">{selected.map(product=><div key={product.id} className={cn("flex gap-3 rounded-[12px] border p-3",hype?"border-zinc-800":"border-slate-200")}><Image src={product.image} alt="" width={80} height={80} className="size-20 rounded-[9px] object-cover"/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{product.name}</p><p className="mt-1 text-sm opacity-60">{formatNaira(product.priceKobo)}</p><div className="mt-2 flex items-center gap-3"><button onClick={()=>update(product.id,-1)} aria-label="Decrease quantity"><Minus size={15}/></button><span className="text-sm font-bold">{quantities[product.id]}</span><button onClick={()=>update(product.id,1)} aria-label="Increase quantity"><Plus size={15}/></button></div></div></div>)}</div>}</div><div className={cn("border-t p-5",hype?"border-zinc-800":"border-slate-200")}><div className="flex justify-between text-sm opacity-60"><span>Subtotal</span><span>{formatNaira(total)}</span></div><div className="mt-3 flex justify-between text-xl font-bold"><span>Total</span><span>{formatNaira(total)}</span></div><Button href={`/checkout/${hype?"noir-drop":"sunday-lunch"}`} tone="purchase" size="lg" className={cn("mt-5 w-full",hype&&"border-lime-300 bg-lime-300 text-zinc-950 hover:bg-lime-200")} disabled={!count}>Continue to checkout <ArrowRight size={18}/></Button></div></aside></>}
  </main>;
}
